### ISSUE TITLE
Failed Table Load

### ISSUE THREAD

**Issue by JimKaidyNASA** [nasa/SIL#17]
Immediately following the successful load and startup of CNT_APP, the error "Fail to load Tbl" is throwing an error code 0xcc000020 indicating a mismatch between the Table file name and the name in the code of the table.  From the log output, it appears that the are case differences and an _ versus a . character.  Not sure if this is the problem or something else.
![image](https://user-images.githubusercontent.com/52501916/66762832-b1e98900-ee74-11e9-9099-6dbf8852ac22.png)

**Comment by SpaceSteve121** [comment]
@JimKaidyNASA I'd like to handle this issue before #16, because I think they probably have the same root cause.

Therefore, as requested in #16, can you post the following information here:
* arguments to the `ECI_TBL_FILEDEF` macro for this table (located in the table's source file)
* value you're using for `PARAM_TBL_PATH_PREFIX` (which can be found in [eci_app_cfg.h](https://github.com/nasa/ECI/blob/master/fsw/src/eci_app_cfg.h#L20))
* version of CFE you're using

**Comment by SpaceSteve121** [comment]
Root cause ended up be mismatched app names between `cfe_es_startup.scr` and `eci_interface.h`. See #16 for additional information.
